### ISSUE TITLE
How should we do if the bottomView is a scrollView?

### ISSUE THREAD

**Issue by lihanst** [AhmedElassuty/IOS-BottomSheet#1]
I found this demo by StackOverFlow but I don't have enough reputation to send a comment on StackOverFlow so I can only ask you the question here.I also want to mimic iOS 10 Map App.In this demo you create a custom view which is a normal view and add it to mainView but the bottom View of Map App in iOS 10 is a tableView.And It can handle the PanGesture to change the contentOffset or the frame of the tableview when it want.I don't  know how to mimic it.I don't know how to handle the PanGesture.Do you know?My English is not very good,but if you observe the Map App carefully,you may understand what I say.Can you reply to me when you are free, thank you very much!

**Comment by AhmedElassuty** [comment]
I just updated the repo with another viewController **ScrollableViewController.swift** that contains a tableView.

The trick is:
1- Set the gesture delegate to the controller.
2- Implement **shouldRecognizeSimultaneouslyWith** func.
In this func, just disable the tableView scrolling property when you don't need it to scroll, and enable it otherwise.

```
    func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        let gesture = (gestureRecognizer as! UIPanGestureRecognizer)
        let direction = gesture.velocity(in: view).y

        let y = view.frame.minY
        if (y == fullView && tableView.contentOffset.y == 0 && direction > 0) || (y == partialView) {
            tableView.isScrollEnabled = false
        } else {
            tableView.isScrollEnabled = true
        }
        
        return false
    }
```
**Note**
If you pulled the controller down then up before the animation completes, the table view won't respond to your first drag, So just make sure that you enable the table view scrolling property on the **completion** callback of the animation. **LINE 77**

I will consider updating my answer on StackOverFlow as soon as possible. Hope it helps and sorry for the late reply.
